
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  reconnect: false
  host: <%= Rails.application.secrets[:database][:host] %>
  port: <%= Rails.application.secrets[:database][:port] %>
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>

development: *default
test: *default
production: *default